[embed_model]
model_name = "BAAI/bge-base-en-v1.5"        # HuggingFace embedding model
cache_folder = "/ragsynapse/store/models"   # Folder to cache the model
embed_batch_size = 1                        # Keep low to prevent OOM errors

[transformations]
chunk_size = 1000       # Characters per Node
chunk_overlap = 100     # Overlap between chunks

[redis]
host_name = "redis"                 # Docker container / hostname for Redis
port_no = 6379                      # Redis port
doc_store_name = "DocStore_v1"      # Namespace for documents
vector_index_name = "VecStore_v1"   # Namespace for vectors
vector_index_prefix = "VecStore_v1" # Prefix for vector index
cache_name = "CacheStore_v1"        # Cache namespace

[paths]
data_path = "/ragsynapse/data/"     # Path to data folder