services:
  ragsynapse:
    build:
      context: .
      dockerfile: Dockerfile
    image: ragsynapse:v3
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/ragsynapse/src
    env_file:
      - .env
    networks:
      - ragsynapse-network
    depends_on:
      redis:
        condition: service_healthy   # waits for Redis to be ready
    volumes:
      - "./:/ragsynapse"

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ragsynapse-network
    volumes:
      - "./store/vecdb:/data"

networks:
  ragsynapse-network:
    driver: bridge